services:
  db:
    container_name: forge_postgres
    build:
      context: .
      dockerfile: containerfile
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      # persist database
      - ./.engine-db:/var/lib/postgresql/data
